# Generated by Django 4.1.6 on 2024-07-11 14:28

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("categoryName", models.CharField(max_length=255)),
                ("categoryDescription", ckeditor.fields.RichTextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blogCategory"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
