# Generated by Django 4.1.6 on 2024-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="categoryDescription",
            field=models.TextField(null=True),
        ),
    ]
