# Generated by Django 4.1.6 on 2024-07-11 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_blogcategory_categorydescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blogCategory"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "blogCategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.blogcategory",
                    ),
                ),
            ],
        ),
    ]
