# Generated by Django 4.1.6 on 2024-07-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
