# Generated by Django 4.1.6 on 2024-07-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_blog_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="blog"),
        ),
    ]
